Bump to 9.6.0.
Need more thinking time, fails to build.

In file included from /var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/src/reductions/cb/cb_actions_mask.cc:5:
/var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/include/vw/core/reductions/cb/cb_actions_mask.h:19:47: error: 'size_t' has not been declared
   19 |   void update_predictions(multi_ex& examples, size_t initial_action_size);
      |                                               ^~~~~~
/var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/src/reductions/cb/cb_actions_mask.cc:15:6: error: no declaration matches 'void VW::reductions::cb_actions_mask::update_predictions(VW::multi_ex&, size_t)'
   15 | void VW::reductions::cb_actions_mask::update_predictions(multi_ex& examples, size_t initial_action_size)
      |      ^~
In file included from /var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/src/reductions/cb/cb_actions_mask.cc:5:
/var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/include/vw/core/reductions/cb/cb_actions_mask.h:19:8: note: candidate is: 'void VW::reductions::cb_actions_mask::update_predictions(VW::multi_ex&, int)'
   19 |   void update_predictions(multi_ex& examples, size_t initial_action_size);
      |        ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/vowpalwabbit-9.6.0/work/vowpal_wabbit-9.6.0/vowpalwabbit/core/include/vw/core/reductions/cb/cb_actions_mask.h:14:7: note: 'class VW::reductions::cb_actions_mask' defined here
   14 | class cb_actions_mask
      |       ^~~~~~~~~~~~~~~

Signed-off-by: Gabriel Linder <gabriel@numberly.com>